### ISSUE TITLE
New permissions do not seem to work.

### ISSUE THREAD

**Issue by tlworks** [sammyvsparks/TagBlocker#1]
As stated in the Title, I've applied the new permissions (again) and people are complaining that they cannot use item tags in chat. Please consider looking into this.

**Comment by tlworks** [comment]
Fixed it by adding the permission: tagblocker.use.item INSTEAD of using the ones in the permission list.

**Comment by sammyvsparks** [comment]
Hmm, I'll look into that in a moment

**Comment by sammyvsparks** [comment]
Oh haha, had them backwards
